spring:
  config:
    import: file:env.properties
  datasource:
    url: jdbc:mysql://${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update